Fix: Company crud update. Inclusion of exceptions
manzano-pje/restaurante pull request #3
Opened 2023-07-14 19:36 UTC by manzano-pje

2023-07-14 21:42 UTC, valdenidelgado requested changes
### Dica de Clean Code:

Se uma classe ja diz o que ela é, não é preciso ser repetido varias vezes no codigo.

Exemplo:
**CompanyServices**

Os metodos não precisam ser **createCompany**, **updateCompany** e **etc**, o **Company** se torna **_redundante_**, pois o nome da classe ja diz do que se trata! poderia ser metodos diretos. **create**() **update**() **delete**() e etc.

Isso serve para os demais arquivos!

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/controllers/CompanyController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Company created.");
Quando você vai retornar um status code **201**, é esperado que seja retornado um _cabeçalho_(**Headers**) contendo o novo endereço que voce inseriu:
Exemplo que ficaria no **headers**: _http://localhost:8080/company/3_
Uma maneira de fazer isso, é utilizando o **URI** e utilizando um metodo ._created()_ do proprio _ResponseEntity_

```suggestion
        URI uri = ServletUriComponentsBuilder.fromCurrentRequest().path("/{id}").buildAndExpand(obj.getId()).toUri();
        return ResponseEntity.created(uri).body("Company created.");
```

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/controllers/CompanyController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(lista);
Acredito que voce pode alterar todos os Object e retornar os objetos corretos no ResponseEntity, como mencionado acima.

Ao inves de usar _HttpStatus.OK_, voce pode usar o proprio metodo do _ResponseEntity_ para isso.
Ele ja ira retornar o **status 200**
Exemplo abaixo
```suggestion
        return ResponseEntity.ok().body(lista);
```

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/controllers/CompanyController.java
> +        return ResponseEntity.status(HttpStatus.OK).body("Company is deleted.");
Geralmente no **delete** _method_, retornamos o _Status Code_ **204**, que é significa **No Content**, e ele é um **Void**

Exemplo abaixo.

```suggestion
        return ResponseEntity.noContent().build();
```

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/dtos/CompanyDto.java
>  @Data
Tomar cuidado com o **@Data** do _lombok_, ele gera _Equals e Hashcode_ para todos os atributos, em classe **DTO** não é necessario. 
Em **Entidade** o Ideal é explicitar que ira fazer o _Equal e Hashcode_ somente no **Id** ou em alguns atributos, mas não em todos

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/dtos/CompanyDto.java
> +        private String name;
Como conversamos, acredito que DTO seja melhor com Record ao inves de classes

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/middleware/CustomExceptionHandler.java
> +public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
Ainda tenho duvida se esse é o melhor formato para retornar exceções personalizadas, recomendo ver outras opções

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/services/CompanyServices.java
> +            List<Company> companyList = companyRepository.findAll();
Não seria mais vantajoso fazer uma busca por Id para verificar se existe a compania ?, poderia utilizar o metodo findById e varia uma busca mais rapida e deixaria mais clean o codigo
Exemplo:
```suggestion
            Company company = companyRepository.findById(companyDto.getId).orElseThrow(() -> new CompanyNotFoundException();
```

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/services/CompanyServices.java
> +            return null;
Porque retorna **null** ? Na declaração diz que ira retornar um _Objeto_ do tipo **Company**. Caso não for retornar nada, usar **void**
```suggestion
            
```

2023-07-14 21:42 UTC, valdenidelgado commented on src/main/java/com/restaurante/services/CompanyServices.java
> +            throw new InternalServerErrorException();
Novamente, **delete** geralmente retorna **void**. você pode remover o **Company** e o **_return no final_**. tambem pode usar o **findById()**

2023-07-14 21:44 UTC, valdenidelgado commented on src/main/java/com/restaurante/record/CompanyRecord.java
> +public record CompanyRecord(
Aqui no record, pode deixar **CompanyDTO** mesmo, pois a ideia ainda é ser um **Data Transfer Object**

2023-07-14 23:46 UTC, manzano-pje commented on src/main/java/com/restaurante/middleware/CustomExceptionHandler.java
> +public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
Pesquisando sobre isso. Até o momento, foi a melor opção que achei

2023-07-14 23:47 UTC, manzano-pje commented on src/main/java/com/restaurante/services/CompanyServices.java
> +            List<Company> companyList = companyRepository.findAll();
Neste caso, se a pesquisa for vazia, ele entra no Throw. Para mim, deve ser ao contrário. Erro caso exista um cnpj.

2023-07-15 00:10 UTC, manzano-pje commented on src/main/java/com/restaurante/controllers/CompanyController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Company created.");
Não está buscando o id cadastrado para completar a URI

2023-07-15 13:23 UTC, valdenidelgado commented on src/main/java/com/restaurante/middleware/CustomExceptionHandler.java
> +public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
Acredito que vale a pena ver sobre o tratamento da excessão do Nelio Alves que comentei, usa uma classe personalizada, retorna o status code usando os Enums. Espero que veja e tenta implementar em um projeto a parte para ver como funciona!

2023-07-17 12:16 UTC, valdenidelgado commented on src/main/java/com/restaurante/controllers/CompanyController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Company created.");
No service, faz retornar o objeto, ai no controller voce acrescente a URI, mas não precisa disponibilizar o objeto

2023-09-01 21:08 UTC, merged